Library Managment System/Controllers/RentalsController.cs
using Library_Managment_System.Dtos;
using Library_Managment_System.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library_Managment_System.Controllers
{
    public class RentalsController : Controller
    {
        // GET: Rentals/Rent
        [Authorize]
        public ActionResult Rent()
        {
            using (Db db = new Db())
            {
                NewRentalDto newrentaldto = new NewRentalDto();


                ViewBag.categories = db.Categories.ToList();
                ViewBag.users = db.Users.ToList();


                return View(newrentaldto);

            }

        }

        [Authorize]
        [HttpPost]
        public ActionResult Rent(NewRentalDto newrentaldto)
        {

            return View();
        }




    }
}

Library Managment System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="~/Home/Index/"><img src="~/Images/Brand.png" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @if (ViewBag.Title == "Books")
                    {
                        <li class="active"> @Html.ActionLink("Books", "Index", "Books", null, new { @class = "navbar-item" }) </li>
                    }
                    else
                    {
                        <li> @Html.ActionLink("Books", "Index", "Books", null, new { @class = "navbar-item" }) </li>
                    }

                    @if (ViewBag.Title == "Rent")
                    {
                        <li class="active"> @Html.ActionLink("Rent", "Rent", "Rentals", null, new { @class = "navbar-item" }) </li>
                    }
                    else
                    {
                        <li> @Html.ActionLink("Rent", "Rent", "Rentals", null, new { @class = "navbar-item" }) </li>

                    }
                    @if (User.IsInRole("Admin"))
                    {
                        if (ViewBag.Title == "AddBook")
                        {
                            <li class="active"> @Html.ActionLink("Add Book", "AddBook", "Books", null, new { @class = "navbar-item" }) </li>
                        }
                        else
                        {
                            <li> @Html.ActionLink("Add Book", "AddBook", "Books", null, new { @class = "navbar-item" }) </li>

                        }
                    }




                    @if (User.IsInRole("Admin"))
                    {
                        if (ViewBag.Title == "Index")
                        {
                            //if he in login page so make login link activated
                            //to make user know that he inside login page
                            <li class="active"><a href="/Category/Index">Manage Category</a></li>

                        }
                        else
                        {
                            //if he doesn't in login page so put log link but with being activated
                            <li><a href="/Category/Index">Manage Category</a></li>


                        }

                    }



                    @if (Request.IsAuthenticated)
                    {
                        <li><a href="/account/logout">Logout</a></li>
                    }
                    else
                    {
                        if (ViewBag.Title == "Login")
                        {
                            //if he in login page so make login link activated
                            //to make user know that he inside login page
                            <li class="active"><a href="/account/login">Login</a></li>
                        }
                        else
                        {
                            //if he doesn't in login page so put log link but with being activated
                            <li><a href="/account/login">Login</a></li>
                        }
                    }



                    @if (Request.IsAuthenticated == false)
                    {
                        if (ViewBag.Title == "CreateAccount")
                        {
                            <li class="active"><a href="/account/CreateAccount">Create Account</a></li>
                        }
                        else
                        {
                            //if he doesn't in login page so put log link but with being activated
                            <li><a href="/account/CreateAccount">Create Account</a></li>
                        }
                    }




                    @if (Request.IsAuthenticated)
                    {
                        if (ViewBag.Title == "User Profile")
                        {
                            //this to show Firstname and Lastname for user
                            <li class="active">@Html.Action("UserNavPartial", "Account")</li>

                        }
                        else
                        {
                            //this to show Firstname and Lastname for user
                            <li>@Html.Action("UserNavPartial", "Account")</li>

                        }

                    }


                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>





    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>